FROM node:16-alpine3.11

RUN npm install -g dockerfile_lint@0.3.4 \
    && apk --no-cache add bash

ENV OUTPUT_DIRECTORY="dockerfile_lint"

SHELL ["/bin/bash", "-c"]
CMD test ! -d /lint-output/$OUTPUT_DIRECTORY && mkdir /lint-output/$OUTPUT_DIRECTORY ; \
    for f in /lint-input/*/*/* ; \
    do \
        SUBDIR_FILE=${f/\/lint-input\/} ; \
        SUBDIRECTORIES=$(cut -d'/' -f 1-2 <<< "$SUBDIR_FILE") ; \
        SUBDIRECTORY=$(cut -d'/' -f 1 <<< "$SUBDIRECTORIES") ; \
        FILENAME=$(cut -d'/' -f 3 <<< "$SUBDIR_FILE") ; \
        test ! -d /lint-output/$OUTPUT_DIRECTORY/$SUBDIRECTORY && mkdir /lint-output/$OUTPUT_DIRECTORY/$SUBDIRECTORY ; \
        test ! -d /lint-output/$OUTPUT_DIRECTORY/$SUBDIRECTORIES && mkdir /lint-output/$OUTPUT_DIRECTORY/$SUBDIRECTORIES ; \
        dockerfile_lint -f "$f" > /lint-output/$OUTPUT_DIRECTORY/$SUBDIRECTORIES/$FILENAME ; \
    done