FROM node:16-alpine3.11

RUN npm install -g dockerfile_lint
RUN apk --no-cache add bash

SHELL ["/bin/bash", "-c"]
CMD test ! -d /lint-output/dockerfile_lint && mkdir /lint-output/dockerfile_lint ; \
    for f in /lint-input/*/*/* ; \
    do \
        SUBDIR_FILE=${f/\/lint-input\/} ; \
        SUBDIRECTORIES=$(cut -d'/' -f 1-2 <<< "$SUBDIR_FILE") ; \
        SUBDIRECTORY=$(cut -d'/' -f 1 <<< "$SUBDIRECTORIES") ; \
        FILENAME=$(cut -d'/' -f 3 <<< "$SUBDIR_FILE") ; \
        test ! -d /lint-output/dockerfile_lint/$SUBDIRECTORY && mkdir /lint-output/dockerfile_lint/$SUBDIRECTORY ; \
        test ! -d /lint-output/dockerfile_lint/$SUBDIRECTORIES && mkdir /lint-output/dockerfile_lint/$SUBDIRECTORIES ; \
        dockerfile_lint -f "$f" > /lint-output/dockerfile_lint/$SUBDIRECTORIES/$FILENAME ; \
    done